#!/bin/bash -uxe

source /etc/kiss-flags/multilib.sh

patch -Np0 -i readline82-001 

# remove rpath from shared objects
sed -i 's|-Wl,-rpath,$(libdir)||g' support/shobj-conf

./configure \
    --prefix=/usr \
    --libdir=/usr/lib32

make SHLIB_LIBS=-lncurses
make DESTDIR="$1" install

rm -rf "$1"/usr/{include,share,bin}
