#!/bin/sh -uxe

source /etc/kiss-flags/multilib.sh

./configure \
    --prefix=/usr \
    --libdir=/usr/lib32 \
    --with-packager=MKiss \
    --with-pagager-bug-reports="https://github.com/mdartmann/mkiss/issues"

make
make DESTDIR="$1" install

rm -rf "$1"/usr/{bin,include,share}
