#!/bin/sh -uxe

export BORG_OPENSSL_PREFIX=/usr/include/openssl

python setup.py build

python setup.py install --root="$1" --optimize=1 --skip-build

install -Dm644 scripts/shell_completions/bash/borg \
    "$1"/usr/share/bash-completion/completions/borg

install -Dm644 scripts/shell_completions/zsh/_borg \
    "$1"/usr/share/zsh/site-functions/_borg

