#!/bin/bash -uxe
# vim:fdm=marker
:>nostrip
# This is based on the Arch Linux nvidia and nvidia-dkms packages.

# Filename of the blob
export blob="NVIDIA-Linux-x86_64-${2}"

#Preserve $1 for funcion
export destdir="$1"

#{{{LINKS
create_links() {
    # create soname links
    find "$destdir" -type f -name '*.so*' ! -path '*xorg/*' -print0 | while read -d $'\0' _lib; do
        _soname=$(dirname "${_lib}")/$(readelf -d "${_lib}" | grep -Po 'SONAME.*: \[\K[^]]*' || true)
        _base=$(echo ${_soname} | sed -r 's/(.*).so.*/\1.so/')
        [[ -e "${_soname}" ]] || ln -s $(basename "${_lib}") "${_soname}"
        [[ -e "${_base}" ]] || ln -s $(basename "${_soname}") "${_base}"
    done
}
#}}}

#{{{PREPARE
sh -e ${blob}.run --extract-only
cd ${blob}

bsdtar -xf nvidia-persistenced-init.tar.bz2

cd kernel

sed -i "s/__VERSION_STRING/${2}/" dkms.conf
sed -i 's/__JOBS/`nproc`/' dkms.conf
sed -i 's/__DKMS_MODULES//' dkms.conf
sed -i '$iBUILT_MODULE_NAME[0]="nvidia"\
DEST_MODULE_LOCATION[0]="/kernel/drivers/video"\
BUILT_MODULE_NAME[1]="nvidia-uvm"\
DEST_MODULE_LOCATION[1]="/kernel/drivers/video"\
BUILT_MODULE_NAME[2]="nvidia-modeset"\
DEST_MODULE_LOCATION[2]="/kernel/drivers/video"\
BUILT_MODULE_NAME[3]="nvidia-drm"\
DEST_MODULE_LOCATION[3]="/kernel/drivers/video"\
BUILT_MODULE_NAME[4]="nvidia-peermem"\
DEST_MODULE_LOCATION[4]="/kernel/drivers/video"' dkms.conf

sed -i 's/NV_EXCLUDE_BUILD_MODULES/IGNORE_PREEMPT_RT_PRESENCE=1 NV_EXCLUDE_BUILD_MODULES/' dkms.conf
cd ..
#}}}

#{{{ OPENCL
install -D -m644 nvidia.icd "${1}/etc/OpenCL/vendors/nvidia.icd"
install -D -m755 "libnvidia-compiler.so.${2}" "${1}/usr/lib/libnvidia-compiler.so.${2}"
install -D -m755 "libnvidia-opencl.so.${2}" "${1}/usr/lib/libnvidia-opencl.so.${2}"

mkdir -p "${1}/usr/share/licenses"
ln -s nvidia-utils "${1}/usr/share/licenses/opencl-nvidia"
#}}}

#{{{NVIDIA-DKMS
install -dm755 "${1}/usr/src"

cp -dr --no-preserve="ownership" kernel "$1"/usr/src/nvidia-${2}
#}}}

#{{{NVIDIA-UTILS

# X driver
install -D -m755 nvidia_drv.so "${1}/usr/lib/xorg/modules/drivers/nvidia_drv.so"

# Wayland/GBM
install -D -m755 libnvidia-egl-gbm.so.1* -t "${1}/usr/lib/"
install -D -m644 15_nvidia_gbm.json "${1}/usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json"
mkdir -p "${1}/usr/lib/gbm"
ln -sr "${1}/usr/lib/libnvidia-allocator.so.${2}" "${1}/usr/lib/gbm/nvidia-drm_gbm.so"

# firmware
install -D -m644 -t "${1}/usr/lib/firmware/nvidia/${2}/" firmware/*.bin

# GLX extension module for X
install -D -m755 "libglxserver_nvidia.so.${2}" "${1}/usr/lib/nvidia/xorg/libglxserver_nvidia.so.${2}"
# Ensure that X finds glx
ln -s "libglxserver_nvidia.so.${2}" "${1}/usr/lib/nvidia/xorg/libglxserver_nvidia.so.1"
ln -s "libglxserver_nvidia.so.${2}" "${1}/usr/lib/nvidia/xorg/libglxserver_nvidia.so"

install -D -m755 "libGLX_nvidia.so.${2}" "${1}/usr/lib/libGLX_nvidia.so.${2}"

# OpenGL libraries
install -D -m755 "libEGL_nvidia.so.${2}" "${1}/usr/lib/libEGL_nvidia.so.${2}"
install -D -m755 "libGLESv1_CM_nvidia.so.${2}" "${1}/usr/lib/libGLESv1_CM_nvidia.so.${2}"
install -D -m755 "libGLESv2_nvidia.so.${2}" "${1}/usr/lib/libGLESv2_nvidia.so.${2}"
install -D -m644 "10_nvidia.json" "${1}/usr/share/glvnd/egl_vendor.d/10_nvidia.json"

# OpenGL core library
install -D -m755 "libnvidia-glcore.so.${2}" "${1}/usr/lib/libnvidia-glcore.so.${2}"
install -D -m755 "libnvidia-eglcore.so.${2}" "${1}/usr/lib/libnvidia-eglcore.so.${2}"
install -D -m755 "libnvidia-glsi.so.${2}" "${1}/usr/lib/libnvidia-glsi.so.${2}"

# misc
install -D -m755 "libnvidia-fbc.so.${2}" "${1}/usr/lib/libnvidia-fbc.so.${2}"
install -D -m755 "libnvidia-encode.so.${2}" "${1}/usr/lib/libnvidia-encode.so.${2}"
install -D -m755 "libnvidia-cfg.so.${2}" "${1}/usr/lib/libnvidia-cfg.so.${2}"
install -D -m755 "libnvidia-ml.so.${2}" "${1}/usr/lib/libnvidia-ml.so.${2}"
install -D -m755 "libnvidia-glvkspirv.so.${2}" "${1}/usr/lib/libnvidia-glvkspirv.so.${2}"
install -D -m755 "libnvidia-allocator.so.${2}" "${1}/usr/lib/libnvidia-allocator.so.${2}"
install -D -m755 "libnvidia-vulkan-producer.so.${2}" "${1}/usr/lib/libnvidia-vulkan-producer.so.${2}"
# Sigh libnvidia-vulkan-producer.so has no SONAME set so create_links doesn't catch it. NVIDIA please fix!
ln -s "libnvidia-vulkan-producer.so.${2}" "${1}/usr/lib/libnvidia-vulkan-producer.so.1"
ln -s "libnvidia-vulkan-producer.so.${2}" "${1}/usr/lib/libnvidia-vulkan-producer.so"

# Vulkan ICD
install -D -m644 "nvidia_icd.json" "${1}/usr/share/vulkan/icd.d/nvidia_icd.json"
install -D -m644 "nvidia_layers.json" "${1}/usr/share/vulkan/implicit_layer.d/nvidia_layers.json"

# VDPAU
install -D -m755 "libvdpau_nvidia.so.${2}" "${1}/usr/lib/vdpau/libvdpau_nvidia.so.${2}"

# nvidia-tls library
install -D -m755 "libnvidia-tls.so.${2}" "${1}/usr/lib/libnvidia-tls.so.${2}"

# CUDA
install -D -m755 "libcuda.so.${2}" "${1}/usr/lib/libcuda.so.${2}"
install -D -m755 "libnvcuvid.so.${2}" "${1}/usr/lib/libnvcuvid.so.${2}"

# NVVM Compiler library loaded by the CUDA driver to do JIT link-time-optimization
install -Dm644 "libnvidia-nvvm.so.${2}" "${1}/usr/lib/libnvidia-nvvm.so.${2}"

# PTX JIT Compiler (Parallel Thread Execution (PTX) is a pseudo-assembly language for CUDA)
install -D -m755 "libnvidia-ptxjitcompiler.so.${2}" "${1}/usr/lib/libnvidia-ptxjitcompiler.so.${2}"

# raytracing
install -D -m755 "libnvoptix.so.${2}" "${1}/usr/lib/libnvoptix.so.${2}"
install -D -m755 "libnvidia-rtcore.so.${2}" "${1}/usr/lib/libnvidia-rtcore.so.${2}"

# NGX
install -D -m755 nvidia-ngx-updater "${1}/usr/bin/nvidia-ngx-updater"
install -D -m755 "libnvidia-ngx.so.${2}" "${1}/usr/lib/libnvidia-ngx.so.${2}"
install -D -m755 _nvngx.dll "${1}/usr/lib/nvidia/wine/_nvngx.dll"
install -D -m755 nvngx.dll "${1}/usr/lib/nvidia/wine/nvngx.dll"

# Optical flow
install -D -m755 "libnvidia-opticalflow.so.${2}" "${1}/usr/lib/libnvidia-opticalflow.so.${2}"

# DEBUG
install -D -m755 nvidia-debugdump "${1}/usr/bin/nvidia-debugdump"

# nvidia-xconfig
install -D -m755 nvidia-xconfig "${1}/usr/bin/nvidia-xconfig"
install -D -m644 nvidia-xconfig.1.gz "${1}/usr/share/man/man1/nvidia-xconfig.1.gz"

# nvidia-bug-report
install -D -m755 nvidia-bug-report.sh "${1}/usr/bin/nvidia-bug-report.sh"

# nvidia-smi
install -D -m755 nvidia-smi "${1}/usr/bin/nvidia-smi"
install -D -m644 nvidia-smi.1.gz "${1}/usr/share/man/man1/nvidia-smi.1.gz"

# nvidia-cuda-mps
install -D -m755 nvidia-cuda-mps-server "${1}/usr/bin/nvidia-cuda-mps-server"
install -D -m755 nvidia-cuda-mps-control "${1}/usr/bin/nvidia-cuda-mps-control"
install -D -m644 nvidia-cuda-mps-control.1.gz "${1}/usr/share/man/man1/nvidia-cuda-mps-control.1.gz"

# nvidia-modprobe
# This should be removed if nvidia fixed their uvm module!
install -D -m4755 nvidia-modprobe "${1}/usr/bin/nvidia-modprobe"
install -D -m644 nvidia-modprobe.1.gz "${1}/usr/share/man/man1/nvidia-modprobe.1.gz"

# nvidia-persistenced
install -D -m755 nvidia-persistenced "${1}/usr/bin/nvidia-persistenced"
install -D -m644 nvidia-persistenced.1.gz "${1}/usr/share/man/man1/nvidia-persistenced.1.gz"
install -Dm644 nvidia-persistenced-init/systemd/nvidia-persistenced.service.template "${1}/usr/lib/systemd/system/nvidia-persistenced.service"
sed -i 's/__USER__/nvidia-persistenced/' "${1}/usr/lib/systemd/system/nvidia-persistenced.service"

# application profiles
install -D -m644 nvidia-application-profiles-${2}-rc "${1}/usr/share/nvidia/nvidia-application-profiles-${2}-rc"
install -Dm644 nvidia-application-profiles-${2}-key-documentation "${1}/usr/share/nvidia/nvidia-application-profiles-${2}-key-documentation"

# new power management support
install -Dm644 systemd/system/*.service -t "${1}/usr/lib/systemd/system"
install -Dm755 systemd/system-sleep/nvidia "${1}/usr/lib/systemd/system-sleep/nvidia"
install -Dm755 systemd/nvidia-sleep.sh "${1}/usr/bin/nvidia-sleep.sh"
install -Dm755 nvidia-powerd "${1}/usr/bin/nvidia-powerd"
install -Dm644 nvidia-dbus.conf "${1}"/usr/share/dbus-1/system.d/nvidia-dbus.conf

# distro specific files must be installed in /usr/share/X11/xorg.conf.d
install -D -m644 "../nvidia-drm-outputclass.conf" "${1}/usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf"

install -Dm644 "../nvidia-utils.sysusers" "${1}/usr/lib/sysusers.d/nvidia-utils.conf"
install -Dm644 "../nvidia.rules" "${1}"/usr/lib/udev/rules.d/60-nvidia.rules
echo "blacklist nouveau" | install -Dm644 /dev/stdin "${1}/usr/lib/modprobe.d/nvidia-utils.conf"
echo "nvidia-uvm" | install -Dm644 /dev/stdin "${1}/usr/lib/modules-load.d/nvidia-utils.conf"

create_links
#}}}
