#!/bin/bash -ue

echo "If you run into trouble with CUDA not being available, run nvidia-modprobe first."
echo "If you use GDM on Wayland, you might have to run systemctl enable --now nvidia-resume.service"
