#!/bin/bash -uxe
export DESTDIR="$1"

git submodule init
git submodule update --recursive

meson setup build \
    ${MESON_OPTIONS} \
    -D update-mimedb=false 

ninja -C build
ninja -C build install

install -Dm755 mime-database.hook "$1"/etc/kiss-hooks/mime-database
