#!/bin/bash -uxe
export DESTDIR="$1"

git submodule init
git submodule update

meson setup build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D gtk_doc=true \
    -D systemd=true \
    -D tests=false \
    --buildtype release || zsh

ninja -C build
ninja -C build install
