#!/bin/sh -uxe
export DESTDIR="$1"

# Do not build ssh_agent to avoid gcr-4 conflict
meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D systemd=enabled \
    -D ssh_agent=false

ninja -C build
ninja -C build install
