#!/bin/sh -uxe

NOCONFIGURE=1 ./autogen.sh

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --libexecdir=/usr/lib \
    --disable-static \
    --with-gtk4

make
make DESTDIR="$1" dbusservicedir=/usr/share/dbus-1/system.d install

echo 'u nm-openconnect - "NetworkManager OpenConnect"' |
    install -Dm644 /dev/stdin "$1/usr/lib/sysusers.d/networkmanager-openconnect.conf"
