#!/bin/sh -uxe

python setup.py build
python setup.py install --root="$1" --optimize=1 --skip-build

install -Dm644 modules/optimus-manager.conf "$1/usr/lib/modprobe.d/optimus-manager.conf"
install -Dm644 systemd/optimus-manager.service "$1/usr/lib/systemd/system/optimus-manager.service"
install -Dm644 optimus-manager.conf "$1/usr/share/optimus-manager.conf"

install -Dm644 systemd/logind/10-optimus-manager.conf "$1/usr/lib/systemd/logind.conf.d/10-optimus-manager.conf"
install -Dm755 systemd/suspend/optimus-manager.py "$1/usr/lib/systemd/system-sleep/optimus-manager.py"

install -Dm644 config/xorg/integrated-mode/integrated-gpu.conf "$1/etc/optimus-manager/xorg/integrated-mode/integrated-gpu.conf"
install -Dm644 config/xorg/nvidia-mode/nvidia-gpu.conf "$1/etc/optimus-manager/xorg/nvidia-mode/nvidia-gpu.conf"
install -Dm644 config/xorg/nvidia-mode/integrated-gpu.conf "$1/etc/optimus-manager/xorg/nvidia-mode/integrated-gpu.conf"
install -Dm644 config/xorg/hybrid-mode/integrated-gpu.conf "$1/etc/optimus-manager/xorg/hybrid-mode/integrated-gpu.conf"
install -Dm644 config/xorg/hybrid-mode/nvidia-gpu.conf "$1/etc/optimus-manager/xorg/hybrid-mode/nvidia-gpu.conf"

install -Dm755 config/xsetup-nvidia.sh "$1/etc/optimus-manager/xsetup-nvidia.sh"
install -Dm755 config/xsetup-hybrid.sh "$1/etc/optimus-manager/xsetup-hybrid.sh"
install -Dm755 config/xsetup-integrated.sh "$1/etc/optimus-manager/xsetup-integrated.sh"

install -Dm755 config/nvidia-enable.sh "$1/etc/optimus-manager/nvidia-enable.sh"
install -Dm755 config/nvidia-disable.sh "$1/etc/optimus-manager/nvidia-disable.sh"
