#!/bin/sh -uxe

export CGO_CFLAGS=${CFLAGS}
export CGO_CXXFLAGS=${CXXFLAGS}
export CGO_LDFLAGS=${LDFLAGS}

export GOFLAGS="-buildmode=pie -trimpath -mod=vendor -modcacherw -ldflags=-linkmode=external"

go generate ./commands

go build .

install -Dm755 git-lfs "$1"/usr/bin/git-lfs
