#!/bin/bash -uxe

./configure \
--prefix=/usr \
--enable-cscope \
--enable-multibyte \
--with-ex-name=vim-ex \
--with-view-name=vim-view \
--disable-perlinterp \
--enable-python3interp \
--disable-canberra \
--disable-rubyinterp \
--disable-netbeans \
--disable-gpm \
--disable-hangulinput \
--disable-xim \
--disable-gui \
--enable-nlw \
--without-x

make
make DESTDIR="$1" install

ln -s vim "$1"/usr/bin/vi
