#!/bin/bash -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D man-pages=enabled \
    --buildtype=plain \
    -D ipc=disabled

ninja -C build
ninja -C build install
