#!/bin/sh -uxe
export DESTDIR="$1"

meson build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    --buildtype release \
    -D profiler=disabled \
    -D installed_tests=false 

ninja -C build
ninja -C build install
