#!/bin/bash -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D BUILD_STATIC_LIBS=OFF \
    -D REQUIRE_CRYPTO_GNUTLS=ON \
    -D REQUIRE_CRYPTO_OPENSSL=OFF \
    -D ENABLE_QTC=ON \
    -D BUILD_DOC=OFF

ninja -C build
ninja -C build install

install -Dm644 completions/bash/qpdf "$1"/usr/share/bash-completion/completions/qpdf
install -Dm644 completions/zsh/_qpdf "$1"/usr/share/zsh/site-functions/_qpdf

rm -rf "$1"/usr/share/docs
