#!/bin/bash -uxe
export DESTDIR="$1"

meson setup build \
	--default-library shared \
	${MESON_OPTIONS}

ninja -C build
ninja -C build install

meson setup build-static \
	${MESON_OPTIONS/-D b_lto=true/} \
	--default-library static

ninja -C build-static
ninja -C build-static install
