#!/bin/bash -uxe

patch -Np1 -i 0001-Make-generate-id-deterministic.patch

NOCONFIGURE=1 ./autogen.sh

./configure \
	--prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
	--with-python=/usr/bin/python \
	--disable-static

sed -i "s/ -shared / $LDFLAGS\0/g" libtool
make
make DESTDIR="$1" install
