#!/bin/bash -uxe

:>nostrip

patch -Np1 -i 0001-Add-support-for-compressing-firmware-in-copy-firmware.patch

install -dm755 "$1"/boot

mkdir -p kernel/x86/microcode
cat amd-ucode/microcode_amd*.bin > kernel/x86/microcode/AuthenticAMD.bin

echo kernel/x86/microcode/AuthenticAMD.bin |
    bsdtar -cnf - -T - |
    bsdtar --null -cf - --format=newc @- > "$1"/boot/amd-ucode.img

make DESTDIR="$1" FIRMWAREDIR=/usr/lib/firmware installcompress

# trigger a microcode reload for configurations not using early updates
echo 'w /sys/devices/system/cpu/microcode/reload - - - - 1' | 
    install -Dm644 /dev/stdin "$1"/usr/lib/tmpfiles.d/linux-firmware.conf
