#!/bin/bash -uxe

# Apply patches (most defaults are taken from Arch Linux)
for i in *.patch; do
    patch -Np1 -i $i
done

autoreconf -fiv

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --mandir=/usr/share/man \
    --sysconfdir=/etc \
    --disable-account-tools-setuid \
    --enable-man \
    --with-fcaps \
    --with-libpam \
    --with-group-name-max-length=32 \
    --with-audit \
    --with-bcrypt \
    --with-yescrypt \
    --without-selinux \
    --without-su

make
fakeroot make DESTDIR="$1" install
make DESTDIR="$1" -C man install

# custom useradd(8) defaults
install -Dm600 useradd.defaults "$1"/etc/defaults/useradd

# systemd units
install -Dm644 shadow.timer "$1"/usr/lib/systemd/system/shadow.timer
install -Dm644 shadow.service "$1"/usr/lib/systemd/system/shadow.service

