#!/bin/sh -uxe

cargo fetch \
    --target "$CARCH-unknown-linux-gnu"

cargo build --release

install -Dm755 target/release/bindgen "$1"/usr/bin/bindgen 

install -Dm644 README.md "$1"/usr/share/doc/bindgen/README.md
