#!/bin/bash -uxe

# Strip manually
:>nostrip

echo $2 > gcc/BASE-VER

mkdir build
cd build

export CFLAGS=${CFLAGS/-Werror=format-security/}
export CXXFLAGS=${CXXFLAGS/-Werror=format-security/}

export CFLAGS_FOR_TARGET="-g -Os -ffunction-sections -fdata-sections"
export CXXFLAGS_FOR_TARGET="-g -Os -ffunction-sections -fdata-sections"

../configure \
    --target=arm-none-eabi \
    --prefix=/usr \
    --with-sysroot=/usr/arm-none-eabi \
    --with-native-system-header-dir=/include \
    --libexecdir=/usr/lib \
    --enable-languages=c,c++ \
    --enable-plugins \
    --disable-decimal-float \
    --disable-libffi \
    --disable-libgomp \
    --disable-libmudflap \
    --disable-libquadmath \
    --disable-libssp \
    --disable-libstdcxx-pch \
    --disable-nls \
    --disable-shared \
    --disable-threads \
    --disable-tls \
    --with-gnu-as \
    --with-gnu-ld \
    --with-system-zlib \
    --with-newlib \
    --with-headers=/usr/arm-none-eabi/include \
    --with-python-dir=share/gcc-arm-none-eabi \
    --with-gmp \
    --with-mpfr \
    --with-mpc \
    --with-isl \
    --enable-libelf \
    --enable-gnu-indirect-function \
    --with-host-libstdcxx="-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm" \
    --with-pkgversion="MKiss" \
    --with-bugurl="https://github.com/mdartmann/mkiss/issues" \
    --with-multilib-list=rmprofile

make INHIBIT_LIBC_CFLAGS="-DUSE_TM_CLONE_REGISTRY=0" -O
make DESTDIR="$1" install -O -j1

# strip target binaries
find "$1"/usr/lib/gcc/arm-none-eabi/$2 "$1"/usr/arm-none-eabi/lib -type f -and \( -name \*.a -or -name \*.o \) -exec arm-none-eabi-objcopy -R .comment -R .note -R .debug_info -R .debug_aranges -R .debug_pubnames -R .debug_pubtypes -R .debug_abbrev -R .debug_line -R .debug_str -R .debug_ranges -R .debug_loc '{}' \;

# strip host binaries
find "$1"/usr/bin/ "$1"/usr/lib/gcc/arm-none-eabi/$2 -type f -and \( -executable \) -exec strip '{}' \;

# Remove files that conflict with host gcc package
rm -r "$1"/usr/share/man/man7
rm -r "$1"/usr/share/info
rm "$1"/usr/lib/libcc1.*
