#!/bin/bash -uxe
export DESTDIR="$1"

sed -i "s|gnome|Adwaita|" icons/meson.build

meson setup build \
    ${MESON_OPTIONS} \
    -D enable-installed-tests=false

ninja -C build
ninja -C build install
