#!/bin/sh -uxe

export PREFIX=/usr
export NV_USE_BUNDLED_LIBJANSSON=0
export OUTPUTDIR=out

patch -Np1 -i nvidia-settings-libxnvctrl_so.patch

make
make DESTDIR="$1" install

install -Dm644 doc/nvidia-settings.desktop "$1"/usr/share/applications/nvidia-settings.desktop
install -Dm644 doc/nvidia-settings.png "$1"/usr/share/pixmaps/nvidia-settings.png

sed \
    -e 's:__UTILS_PATH__:/usr/bin:' \
    -e 's:__PIXMAP_PATH__:/usr/share/pixmaps:' \
    -e 's/__NVIDIA_SETTINGS_DESKTOP_CATEGORIES__/Settings;HardwareSettings;/' \
    -e 's/Icon=.*/Icon=nvidia-settings/' \
    -i "${1}/usr/share/applications/nvidia-settings.desktop"

install -Dm 644 src/libXNVCtrl/*.h -t "${1}/usr/include/NVCtrl"
install -d "${1}/usr/lib"
cp -Pr src/out/libXNVCtrl.* -t "${1}/usr/lib"

