#!/bin/bash -uxe
export DESTDIR="$1"

meson setup build \
    ${MESON_OPTIONS/-D b_lto=true/} \
    -D ps=enabled \
    -D nautilus=false \
    -D dvi=disabled 

ninja -C build
ninja -C build install
