#!/bin/bash -uxe
export DESTDIR="$1"

meson build AppStream-"$2" \
    --prefix=/usr \
    --libexecdir=lib \
    -D qt=true \
    -D vapi=true \
    -D compose=true

ninja -C build
ninja -C build install
