#!/bin/bash -uxe
export DESTDIR="$1"

meson setup build \
    --prefix=/usr \
    --buildtype=plain \
    --auto-features=enabled \
    --wrap-mode=nodownload \
    -D systemd=enabled \
    -D tests=disabled \
    -D jack=disabled \
    -D wireplumber=disabled

ninja -C build
ninja -C build install
