#!/bin/bash -uxe
export DESTDIR="$1"

meson setup build \
	-D doc=disabled \
	-D cache-build=disabled \
	${MESON_OPTIONS}

ninja -C build
ninja -C build install

install -Dm755 fontconfig.kiss-hook "$1"/etc/kiss-hooks/fontconfig
