#!/bin/sh -uxe

go build \
    -trimpath \
    -buildmode=pie \
    -mod=readonly \
    -modcacherw \
    -ldflags="-linkmode external -extldflags \"${LDFLAGS}\"" \
    -o dist/gdu \
    github.com/dundee/gdu/v5/cmd/gdu

install -Dm755 dist/gdu "$1"/usr/bin/gdu
install -Dm644 gdu.1 "$1"/usr/share/man/man1/gdu.1
