#!/bin/bash -uxe

go build \
    -trimpath \
    -buildmode=pie \
    -mod=readonly \
    -modcacherw \
    -ldflags="-linkmode external 
        -extldflags \"${LDFLAGS}\" 
        -X github.com/dundee/gdu/v5/build.VERSION=${2} 
        -X github.com/dundee/gdu/v5/build.User=mkiss 
        -X github.com/dundee/gdu/v5/build.Time=$(date +%s)" \
    -o dist/gdu \
    github.com/dundee/gdu/v5/cmd/gdu

install -Dm755 dist/gdu "$1"/usr/bin/gdu
install -Dm644 gdu.1 "$1"/usr/share/man/man1/gdu.1
