#!/bin/bash -uxe
export DESTDIR="$1"
export CFLAGS+=" -ffat-lto-objects"
export CXXFLAGS+=" -ffat-lto-objects"

meson build \
    ${MESON_OPTIONS} \
    -D default_bus=dbus-broker 

ninja -C build
ninja -C build install
