#!/bin/sh -uxe

# Fix libz-sys
export CFLAGS+=" -ffat-lto-objects -lz-ng"
export RUSTFLAGS+=" -lz-ng -L /usr/lib"

cargo fetch \
	--locked \
	--target ${CARCH}-unknown-linux-gnu 

cargo build \
	--release \
	--frozen 

install -Dm755 target/release/starship -t "$1/usr/bin"

install -dm755 "$1"/usr/share/{bash-completion/completions,zsh/site-functions}/

./target/release/starship completions bash > "$1"/usr/share/bash-completion/completions/starship

./target/release/starship completions zsh > "$1"/usr/share/zsh/site-functions/_starship

# Fix erraneous libz-sys install location
rm -rf "${1:?}"/home
