#!/bin/bash -uxe

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --sbindir=/usr/bin \
    --disable-db

make
make DESTDIR="$1" SCONFDIR=/etc/security install

mkdir "$1"/etc/pam.d

mkdir "$1"/usr/lib/tmpfiles.d
echo 'd /run/faillock 0755 root root -' > "$1"/usr/lib/tmpfiles.d/pam.conf

for i in *.pam; do
    install -Dm644 "$i" "$1"/etc/pam.d/"${i//.pam}"
done
