#!/bin/bash -uxe

NOCONFIGURE=1 ./autogen.sh

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --localstatedir=/var \
    --with-rcdir=no \
    --enable-avahi \
    --with-browseremoteprotocols=DNSSD,CUPS \
    --enable-auto-setup-driverless \
    --with-test-font-path=/usr/share/fonts/liberation/LiberationSans-Regular.ttf

make
make DESTDIR="$1" install

install -Dm644 utils/cups-browsed.service "${1}"/usr/lib/systemd/system/cups-browsed.service
sed -i "s|/usr/sbin/cups-browsed|/usr/bin/cups-browsed|" "${1}"/usr/lib/systemd/system/cups-browsed.service

