#!/bin/bash -uxe
export DESTDIR="$1"

rm -rf Telegram/ThirdParty/libtgvoid/webrtc_dsp/absl

cmake -B build -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_BUILD_TYPE=Release \
    -D TDESKTOP_API_ID=611335 \
    -D TDESKTOP_API_HASH=d524b414d21f4d37f08684c1df41ac9c

ninja -C build 
ninja -C build install
